name: Setup
description: 'Setup project'

outputs:
  readonly-token:
    description: 'Readonly token'
    value: ${{ steps.readonly-token.outputs.token }}
  writable-token:
    description: 'Writable token'
    value: ${{ steps.writable-token.outputs.token }}

runs:
  using: 'composite'
  steps:
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Build devShell
      run: |
        nix print-dev-env > result-devShell.sh
        echo "BASH_ENV=$PWD/result-devShell.sh" >> $GITHUB_ENV
      shell: bash
    - name: Cache cargo target
      uses: actions/cache@v4
      with:
        path: ./target
        key: cargo-cache-20250204-1-${{ github.sha }}
        restore-keys: |
          cargo-cache-20250204-1-
    - name: Cache cargo home
      uses: actions/cache@v4
      with:
        path: ~/.cargo
        key: cargo-home-20250204-1-${{ github.sha }}
        restore-keys: |
          cargo-home-20250204-1-
