[package]
name = "webschembly-compiler-locate"
authors.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
