[package]
edition = "2021"
name = "webschembly-runtime"
version = "0.1.0"

[dependencies]
log = "0.4.26"
webschembly-compiler = {path = "../webschembly-compiler"}

[lib]
crate-type = ["cdylib", "rlib"]
