[package]
edition = "2024"
name = "webschembly-compiler-cli"
version = "0.1.0"

[dependencies]
anyhow = "1.0.95"
clap = {version = "4.5.30", features = ["derive"]}
webschembly-compiler = {path = "../webschembly-compiler"}
